#!/bin/bash
# This script removes files older than $HOURS in 
# /u01/app/oracle/admin/<db>/adump
# Which is the default destination for Oracle database audit files.
#
# This script is intended to run daily via /etc/cron.daily
#
# 08062011 FH - Creation
#
# 168 = 24 * 7; a week
HOURS=168
for DIR in /u01/app/oracle/admin/*/adump; do
  if [ -d "$DIR" ]; then
    /usr/sbin/tmpwatch -maf $HOURS "$DIR"
  fi
done
